baseURL = "https://alexpeta.github.io/"
title = "Alex Peta's Blog"
author = "Alex Peta"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "harbor"

[Author]
  name = "Alex Peta"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "/archives/"
  weight = 3

[[params.social]]
  name= "Twitter"
  url="https://twitter.com/alexpeta"
  icon="fab fa-twitter"

[[params.social]]
  name= "GitHub"
  url="https://github.com/alexpeta"
  icon="fab fa-github"

[[params.social]]
  name= "linkedin"
  url="https://www.linkedin.com/in/alexpeta/"
  icon="fab fa-linkedin"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "logo2.png"
    width = 50
    height = 50
    alt = "Logo"